### ISSUE TITLE
How to use BIC score

### ISSUE THREAD

**Issue by MAX00008888** [cmu-phil/causal-learn#23] opened 2022-04-02 13:43 UTC
Hi, sorry to bother you@kunwuz ,

I'm having some problems using the bic score. It always get a big number  like -6951.8887543026485   
` rewards = local_score_BIC(data,0,[0])` 

The data is created by myself. I don't know the eaxt meaning of i and Pai.

**Comment by MAX00008888** [comment] 2022-04-02 14:05
Can I get a score in the range of 0~1

**Comment by jdramsey** [comment] 2022-04-02 16:31
BIC scores are not in that range of course, but what is you goal?

**Comment by MAX00008888** [comment] 2022-04-03 02:58
I want to do causal RL. So I tkae the BIC score as the rewards. @jdramsey

**Comment by jdramsey** [comment] 2022-04-03 03:35
Hmmm... I don't think BIC makes for a good loss function...first of all it's not guaranteed even to be strictly non-negative. What other loss functions have you considered?

**Comment by jdramsey** [comment] 2022-04-03 03:37
Is this a model loss function or a node loss function? Or a parameter loss function?

**Comment by MAX00008888** [comment] 2022-04-03 03:43
It’s a model loss function. Critic loss and actor loss

**Comment by MAX00008888** [comment] 2022-04-03 03:46
So normally we get a large number when using bic score?

**Comment by jdramsey** [comment] 2022-04-03 04:25
I think the problem is, you don't get something interpretable as a loss. BIC as a function (see the Scwharz or a later famous paper I forget by whom now though I could look it up for you), the only thing you know for sure about BIC is that it is optimized (in different directions and with different formulas depending on the software, adjusted by a multiplicative term) for a model in the true Markov equivalence class. The optimal value is unique for a given dataset, so you need to always compare BIC scores for the same data, not for different data, including even for the same sample size. The optimum value could the highest score, therefore, or the lowest score, depending on the software, so you're have to check. Also, the optimum value could be a positive number (of arbitrary size) or a negative number (or arbitrary size) for a particular dataset. My impression of loss is that you want to have a loss of zero for the correct model and nonzero (preferably positive) for incorrect models, so from everything I know so far BIC is ill-suited to this purpose. Though you may be able to convince me otherwise.

**Comment by jdramsey** [comment] 2022-04-03 05:36
I should add that it hardly ever is true that BIC score for a given dataset are all positive or all negative, yet the optimum score property still holds. Treating BIC as a loss function runs the risk of counting very positive and very negative scores as equally bad, which they are not. In fact, if the score is "high is better" very positive BIC scores will be very good, and zero BIC scores will be relatively bad.

**Comment by MAX00008888** [comment] 2022-04-03 06:13
Thank you sooooo much for your reply!!! It's very useful.

Best,
Max

**Comment by jdramsey** [comment] 2022-04-03 06:38
You're welcome!

**Comment by MAX00008888** [comment] 2022-04-03 06:54
It occurs to me that can I use the BIC score to evaluate a graph and get the score?

**Comment by jdramsey** [comment] 2022-04-03 07:27
Yes, that's a perfectly reasonable thing to do.

**Comment by MAX00008888** [comment] 2022-04-03 07:28
How can I do this in your library. All I can see is using data to get BIC score.

**Comment by jdramsey** [comment] 2022-04-03 07:59
Hmmm... that's what I thought you meant. What score do you mean?

**Comment by jdramsey** [comment] 2022-04-03 08:00
By the way, I mainly work on a different project--same department. Hopefully someone working on this project can help you as well. Also, I may fall asleep soon.

**Comment by MAX00008888** [comment] 2022-04-03 08:02
Thank you so much for your time. I will do more research later.

**Comment by kunwuz** [comment] 2022-04-03 08:05
Thanks for your detailed reply and help, Joe :) @MAX00008888 , BIC score is used for model selection, which is basically for graphical models in our case. It might be more helpful if you could kindly provide more specific information related to your questions.

**Comment by MAX00008888** [comment] 2022-04-03 08:08
Ok, Thank you so much for your reply. I wonder how can I get BIC score according to a graph. Lije this way.

![image](https://user-images.githubusercontent.com/101794848/161418438-7365bd7f-9cf1-4a7d-8c38-339d1c0e071c.png)

**Comment by MAX00008888** [comment] 2022-04-03 08:11
In the last part, I want to get a BIC score according to `output_graph `
` from cdt.data import AcyclicGraphGenerator
        generator = AcyclicGraphGenerator('linear', npoints=100, nodes=8)
        data,graph = generator.generate()
        matrix = nx.adjacency_matrix(graph).todense()

        # 真实图赋值给 action
        action = torch.Tensor(matrix).to(device)

        # 推测图
        model = GES()
        output_graph = model.predict(data)

        # 获得BIC评分  待完成
        from causallearn.score.LocalScoreFunction import local_score_BIC
        # from causallearn.search.ScoreBased.GES import ges
        # Record = ges(data, 'local_score_BIC', maxP=5)
        rewards =  local_score_BIC(data, 1, [1])`

**Comment by kunwuz** [comment] 2022-04-03 08:22
I see, thanks for your information. If I understand correctly, you could refer to https://github.com/cmu-phil/causal-learn/blob/ed86eb7bac8973caaf758ed4bb2e6f5ec7f37850/causallearn/utils/GESUtils.py#L58 for obtaining 'global' BIC for a 'graph'.

**Comment by MAX00008888** [comment] 2022-04-03 08:25
Yes, that's what I want. I will try this later. Thank you so much! @kunwuz @jdramsey

**Comment by MAX00008888** [comment] 2022-04-03 08:38
Is G a general graph or DiGraph?

**Comment by kunwuz** [comment] 2022-04-03 08:40
A GeneralGraph, and its usage could be found here https://github.com/cmu-phil/causal-learn/blob/ed86eb7bac8973caaf758ed4bb2e6f5ec7f37850/causallearn/search/ScoreBased/GES.py#L98

**Comment by MAX00008888** [comment] 2022-04-03 08:42
How Can I transfer Digraph into general graph?

**Comment by kunwuz** [comment] 2022-04-03 08:52
If I remember correctly, Digraph is a subclass of the general graph. Perhaps related files about graph classes (e.g., dag.py) could be helpful.

**Comment by MAX00008888** [comment] 2022-04-03 09:00
Thanks a lot!!! Now I'm running this, but get a bug.
`Traceback (most recent call last):
  File "D:/pythonProject4/CRL.py", line 80, in <module>
    'action_diff': continuous_action_diff_scorer
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\d3rlpy\base.py", line 423, in fit
    callback,
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\d3rlpy\base.py", line 628, in fitter
    loss = self.update(batch)
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\d3rlpy\base.py", line 738, in update
    loss = self._update(batch)
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\d3rlpy\algos\td3.py", line 194, in _update
    critic_loss = self._impl.update_critic(batch)
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\d3rlpy\torch_utility.py", line 317, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\d3rlpy\torch_utility.py", line 299, in wrapper
    return f(self, *tensors, **kwargs)
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\d3rlpy\algos\torch\ddpg_impl.py", line 158, in update_critic
    loss = self.compute_critic_loss(batch, q_tpn)
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\d3rlpy\algos\torch\ddpg_impl.py", line 199, in compute_critic_loss
    rewards = score_g(data, G, 'local_score_BIC', parameters)
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\causallearn\utils\GESUtils.py", line 62, in score_g
    delta_score = feval([score_func, Data, i, PA, parameters])
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\causallearn\utils\GESUtils.py", line 21, in feval
    return local_score_BIC(parameters[1], parameters[2], parameters[3], parameters[4])
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\causallearn\score\LocalScoreFunction.py", line 34, in local_score_BIC
    PA = Data[:, PAi]
  File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\numpy\matrixlib\defmatrix.py", line 193, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
`
Is something wrong with my data. my code is as follows:
`from causallearn.score.LocalScoreFunction import local_score_BIC
        from causallearn.utils.GESUtils import score_g
        from causallearn.search.ScoreBased.GES import ges
        Record = ges(data, 'local_score_BIC', maxP=5)
        parameters = {'kfold': 10, 'lambda_value': 0.01}
        G= Record['G']
        rewards = score_g(data, G, 'local_score_BIC', parameters)`

**Comment by kunwuz** [comment] 2022-04-03 16:32
Hi, I'm not sure about that. Could you please provide a reproducible case?

**Comment by kunwuz** [comment] 2022-04-03 19:33
Since the major questions regarding the current topic have been answered, I will temporarily close this issue for a more convenient reference for others. Please feel free to reopen it or create another one if there are any further questions.

**Closed** 2022-04-03 19:33 UTC
